### ISSUE TITLE
Oracle for v1 pools tech description

### ISSUE THREAD

**Issue by tjcloa** [DistributedCollective/oracle-based-amm#32]
It is basically implemented, the code is under review, tests are upcoming
The task statement: https://docs.google.com/document/d/1acGmVgz3ZTLuRQRx-82tMIZiNYepvqOWoWvs0k_EIFc
Implementation is here: https://github.com/DistributedCollective/oracle-based-amm/tree/v1-pool-oracle
Description of the contract changes from @rahne-sinclair  :
https://docs.google.com/document/d/1RmtDoFLpyNwGXjhwnmv1Qx4Gp6XKGSglepZcvjj7R7Q
the right person to go for details is @Rahne#7236 (discord)

**Comment by jjmr007** [comment]
Already taken in the issue: https://github.com/DistributedCollective/oracle-based-amm/issues/41
Card: https://github.com/orgs/DistributedCollective/projects/4#card-63392077
